# Generated by Django 3.2.4 on 2021-07-16 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('a_name', models.CharField(default='', max_length=200)),
                ('a_image', models.ImageField(default='', upload_to='Property/images/agency/')),
                ('a_address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('mobile', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('profile', models.ImageField(default='', upload_to='Property/images/profile')),
                ('user_type', models.CharField(choices=[('user', 'user'), ('broker', 'broker')], default='user', max_length=10)),
                ('details', models.CharField(max_length=200)),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=255)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.brokercategory')),
            ],
        ),
    ]
