# Generated by Django 3.2.4 on 2021-07-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
