# Generated by Django 3.2.4 on 2021-09-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpropertyform',
            name='cate_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Property.brokercategory'),
        ),
        migrations.AddField(
            model_name='addpropertyform',
            name='subcate_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Property.brokersubcategory'),
        ),
    ]
