# Generated by Django 3.2.4 on 2021-07-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPropertyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyTitle', models.CharField(max_length=255)),
                ('propertyType', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('propertyDescription', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('Neighborhood', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('areaSize', models.CharField(max_length=255)),
                ('sizePrefix', models.CharField(max_length=255)),
                ('landArea', models.CharField(max_length=255)),
                ('landAreaSize', models.CharField(max_length=255)),
                ('bedRooms', models.CharField(max_length=255)),
                ('bathRooms', models.CharField(max_length=255)),
                ('builtYear', models.CharField(max_length=255)),
            ],
        ),
    ]
