# Generated by Django 3.2.4 on 2021-09-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
