# Generated by Django 3.2.4 on 2021-08-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_auto_20210812_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='u_id',
        ),
    ]
