# Generated by Django 3.2.4 on 2021-07-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_addpropertyform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddPropertyForm',
        ),
    ]
