# Generated by Django 3.2.4 on 2021-07-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Property', '0002_delete_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_insert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('user_type', models.CharField(choices=[('user', 'User'), ('broker', 'Broker')], max_length=130)),
            ],
        ),
    ]
