# Generated by Django 3.2.4 on 2021-09-08 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Property', '0003_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpropertyform',
            name='Neighborhood',
        ),
        migrations.RemoveField(
            model_name='addpropertyform',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='addpropertyform',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='addpropertyform',
            name='landAreaSize',
        ),
        migrations.RemoveField(
            model_name='addpropertyform',
            name='landarea',
        ),
        migrations.RemoveField(
            model_name='addpropertyform',
            name='sizeprefix',
        ),
        migrations.AddField(
            model_name='addpropertyform',
            name='aid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Property.agency'),
        ),
        migrations.AddField(
            model_name='addpropertyform',
            name='propertybrochure',
            field=models.ImageField(default='', upload_to='Property/images/brochure'),
        ),
        migrations.AddField(
            model_name='addpropertyform',
            name='propertyplanimage',
            field=models.ImageField(default='', upload_to='Property/images/plan'),
        ),
        migrations.AddField(
            model_name='addpropertyform',
            name='propertyvideo',
            field=models.ImageField(default='', upload_to='Property/images/video'),
        ),
        migrations.AddField(
            model_name='addpropertyform',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addpropertyform',
            name='cate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.brokercategory'),
        ),
        migrations.AlterField(
            model_name='addpropertyform',
            name='propertyimage',
            field=models.ImageField(upload_to='Property/images/property'),
        ),
        migrations.AlterField(
            model_name='addpropertyform',
            name='subcate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.brokersubcategory'),
        ),
    ]
