# Generated by Django 3.2.4 on 2021-07-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_user_insert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_insert',
        ),
    ]
