# Generated by Django 3.2.4 on 2021-08-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0004_addpropertyform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpropertyform',
            old_name='areaSize',
            new_name='areasize',
        ),
        migrations.RenameField(
            model_name='addpropertyform',
            old_name='bathRooms',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='addpropertyform',
            old_name='bedRooms',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='addpropertyform',
            old_name='builtYear',
            new_name='builtyear',
        ),
        migrations.RenameField(
            model_name='addpropertyform',
            old_name='landArea',
            new_name='landarea',
        ),
        migrations.RenameField(
            model_name='addpropertyform',
            old_name='sizePrefix',
            new_name='sizeprefix',
        ),
        migrations.AddField(
            model_name='addpropertyform',
            name='propertyimage',
            field=models.ImageField(default='', upload_to='Property/images/property'),
        ),
    ]
