# Generated by Django 3.2.4 on 2021-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0005_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency',
            field=models.ImageField(default='', upload_to='Property/images/'),
        ),
    ]
