# Generated by Django 3.2.4 on 2021-07-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0006_agency_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='agency',
            new_name='image',
        ),
    ]
